In [2]:
## pytorch

In [3]:
print('Hello World!')

Hello World!


In [4]:
!nvidia-smi


Mon Mar  2 10:46:02 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   47C    P8             11W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [5]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [6]:
print(torch.__version__)

2.10.0+cu128


## Introduction to Tensors

### creating tensors

In [7]:
scalar = torch.tensor(7)

In [8]:
scalar

tensor(7)

In [9]:
scalar.item()

7

In [10]:
scalar.ndim

0

In [11]:
vector = torch.tensor([2,2])

In [12]:
vector

tensor([2, 2])

In [13]:
vector.shape


torch.Size([2])

In [14]:
scalar.shape

torch.Size([])

In [15]:
vector.ndim

1

In [16]:
matrix = torch.tensor([[1,2],[2,3],[4,5]])

In [17]:
matrix.ndim

2

In [18]:
matrix.shape

torch.Size([3, 2])

In [19]:
tensor = torch.tensor([[[1,2,3]
                        ,[4,5,6]
                        ,[7,8,9]],
                       [[2,2,3]
                        ,[4,3,6]
                        ,[7,1,9]]])

In [20]:
tensor.ndim

3

In [21]:
tensor.shape

torch.Size([2, 3, 3])

### Random Tensors

Why random tensors?

Random tensors are important beause, the way many neural network learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> Look at data -> update random numbers -> look at data -> update again and so on`

In [22]:
random_tensor = torch.rand(3,4)
#random tensor of size 3,4

In [23]:
random_tensor

tensor([[0.0935, 0.8238, 0.2156, 0.5711],
        [0.3806, 0.0132, 0.9100, 0.8171],
        [0.9047, 0.4402, 0.3480, 0.0972]])

In [24]:
random_tensor.ndim

2

In [25]:
random_tensor.shape

torch.Size([3, 4])

In [26]:
random_tensor = torch.rand(10,2,10)

In [27]:
random_tensor

tensor([[[0.5407, 0.0782, 0.7918, 0.4736, 0.6689, 0.7019, 0.7325, 0.5649,
          0.1486, 0.8240],
         [0.2628, 0.0546, 0.6011, 0.8245, 0.0533, 0.1072, 0.1848, 0.5110,
          0.7118, 0.1934]],

        [[0.7773, 0.5866, 0.4510, 0.9127, 0.9817, 0.5777, 0.6368, 0.5080,
          0.9716, 0.9138],
         [0.9558, 0.3232, 0.7795, 0.8592, 0.2379, 0.7839, 0.5274, 0.7664,
          0.8481, 0.3547]],

        [[0.6558, 0.0049, 0.1669, 0.7898, 0.1046, 0.4258, 0.9889, 0.7643,
          0.8466, 0.2914],
         [0.8240, 0.1348, 0.4121, 0.4400, 0.2897, 0.8640, 0.4662, 0.7961,
          0.4332, 0.8238]],

        [[0.2513, 0.6145, 0.1250, 0.6968, 0.9656, 0.6148, 0.7471, 0.4821,
          0.8209, 0.8412],
         [0.7706, 0.5096, 0.2203, 0.1332, 0.2333, 0.6953, 0.9924, 0.7061,
          0.9827, 0.2466]],

        [[0.5206, 0.9784, 0.3123, 0.2501, 0.0904, 0.6726, 0.1477, 0.5208,
          0.1521, 0.0283],
         [0.3359, 0.5151, 0.1677, 0.5918, 0.7559, 0.3313, 0.5351, 0.5797,
         

In [28]:
random_image_size_tensor = torch.rand(size = (224,224,3))

In [29]:
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [30]:
zeros = torch.zeros(size = (3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [31]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [32]:
ones.dtype

torch.float32

In [33]:
ones = torch.ones(3,3,3,3,3,3)
ones


tensor([[[[[[1., 1., 1.],
            [1., 1., 1.],
            [1., 1., 1.]],

           [[1., 1., 1.],
            [1., 1., 1.],
            [1., 1., 1.]],

           [[1., 1., 1.],
            [1., 1., 1.],
            [1., 1., 1.]]],


          [[[1., 1., 1.],
            [1., 1., 1.],
            [1., 1., 1.]],

           [[1., 1., 1.],
            [1., 1., 1.],
            [1., 1., 1.]],

           [[1., 1., 1.],
            [1., 1., 1.],
            [1., 1., 1.]]],


          [[[1., 1., 1.],
            [1., 1., 1.],
            [1., 1., 1.]],

           [[1., 1., 1.],
            [1., 1., 1.],
            [1., 1., 1.]],

           [[1., 1., 1.],
            [1., 1., 1.],
            [1., 1., 1.]]]],



         [[[[1., 1., 1.],
            [1., 1., 1.],
            [1., 1., 1.]],

           [[1., 1., 1.],
            [1., 1., 1.],
            [1., 1., 1.]],

           [[1., 1., 1.],
            [1., 1., 1.],
            [1., 1., 1.]]],


          [[[1., 1., 1.],
    

### creating a range of tensors

In [34]:
torch.range(0,10)

/tmp/ipython-input-275/497691777.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [35]:
range = torch.arange(start = 0,end=1000, step = 67)
range

tensor([  0,  67, 134, 201, 268, 335, 402, 469, 536, 603, 670, 737, 804, 871,
        938])

In [36]:
zeros = torch.zeros_like(input = range)
zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [37]:
zeros = torch.zeros_like(input = ones)
zeros

tensor([[[[[[0., 0., 0.],
            [0., 0., 0.],
            [0., 0., 0.]],

           [[0., 0., 0.],
            [0., 0., 0.],
            [0., 0., 0.]],

           [[0., 0., 0.],
            [0., 0., 0.],
            [0., 0., 0.]]],


          [[[0., 0., 0.],
            [0., 0., 0.],
            [0., 0., 0.]],

           [[0., 0., 0.],
            [0., 0., 0.],
            [0., 0., 0.]],

           [[0., 0., 0.],
            [0., 0., 0.],
            [0., 0., 0.]]],


          [[[0., 0., 0.],
            [0., 0., 0.],
            [0., 0., 0.]],

           [[0., 0., 0.],
            [0., 0., 0.],
            [0., 0., 0.]],

           [[0., 0., 0.],
            [0., 0., 0.],
            [0., 0., 0.]]]],



         [[[[0., 0., 0.],
            [0., 0., 0.],
            [0., 0., 0.]],

           [[0., 0., 0.],
            [0., 0., 0.],
            [0., 0., 0.]],

           [[0., 0., 0.],
            [0., 0., 0.],
            [0., 0., 0.]]],


          [[[0., 0., 0.],
    

### Tensor Datatypes

**Note:** Tensor datatypes is one of the 3 big erros that you'll run into with pytorch and deep learning.

1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on right device.(if two tensors on differnet devices eg- one is on cpu and another on gpu(cuda), and they tries to interact with each other)

In [38]:
float_32_tensor = torch.tensor((3.0,6.00,9.),
                               dtype = torch.int64, # what datatype is the tensor (eg. float32, float64, float16, int32...)
                               device = "cpu", #what device is the tensor on
                               requires_grad = False) # whether or not to track gradient with this tensor's operations

float_32_tensor

tensor([3, 6, 9])

In [39]:
float_32_tensor.dtype

torch.int64

In [40]:
float_16_tensor = float_32_tensor.type(torch.float16)

In [41]:
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [42]:
float_16_tensor*float_32_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

### Tensor attributes for getting information from tensors

tensor.dtype

tensor.shape

tensor.device

In [43]:
some_tensor = torch.rand((4,6), device = 'cpu')
some_tensor

tensor([[0.3302, 0.2176, 0.3935, 0.1803, 0.3858, 0.4185],
        [0.4202, 0.7437, 0.3062, 0.9019, 0.0431, 0.2908],
        [0.2229, 0.4783, 0.6423, 0.9857, 0.7350, 0.6823],
        [0.2719, 0.3734, 0.6418, 0.3289, 0.1808, 0.1214]])

In [44]:
print(some_tensor)
print(f'Datatype:{some_tensor.dtype}')
print(f'Shape:{some_tensor.shape}')
print(f'Device:{some_tensor.device}')

tensor([[0.3302, 0.2176, 0.3935, 0.1803, 0.3858, 0.4185],
        [0.4202, 0.7437, 0.3062, 0.9019, 0.0431, 0.2908],
        [0.2229, 0.4783, 0.6423, 0.9857, 0.7350, 0.6823],
        [0.2719, 0.3734, 0.6418, 0.3289, 0.1808, 0.1214]])
Datatype:torch.float32
Shape:torch.Size([4, 6])
Device:cpu


### Manipulating Tensors (Tensors Operations)

Tensors operations include:
* Additions
* Subtractions
* Multiplications
* Divisions
* Matrix Multiplications

In [45]:
tensor1  = torch.tensor([1.,2.,3.])
tensor1 += 10
tensor1

tensor([11., 12., 13.])

In [46]:
tensor1 * 10

tensor([110., 120., 130.])

In [47]:
tensor1

tensor([11., 12., 13.])

In [48]:
tensor1 - 20

tensor([-9., -8., -7.])

In [49]:
# try out PyTorch in-built function

torch.mul(tensor1,10)

tensor([110., 120., 130.])

In [50]:
tensor1

tensor([11., 12., 13.])

In [51]:
tensor1 * torch.tensor((12))



tensor([132., 144., 156.])

In [52]:
tensor1 * 12

tensor([132., 144., 156.])

In [53]:
tensor1 * torch.tensor((12,21,22))

tensor([132., 252., 286.])

In [54]:
torch.matmul(tensor1 , torch.tensor([3.,2.,1.]))

tensor(70.)

In [55]:
torch.matmul(torch.rand(3,2), torch.rand(2,4))

tensor([[0.1383, 0.3067, 0.0794, 0.3461],
        [0.1649, 0.5615, 0.1030, 0.6723],
        [0.1866, 0.4423, 0.1084, 0.5047]])

In [56]:
tensor1  = torch.tensor([[1.,2.,3.]])
tensor1


tensor([[1., 2., 3.]])

In [57]:
tensor2 = torch.tensor([[5.,6.,7.0]])
tensor2

tensor([[5., 6., 7.]])

In [58]:
tensor1 @ tensor2.T # @ -> tensor.matmul() , .T -> transpose

tensor([[38.]])

#### Finding the min, max, mean, sum etc. (Tensor Aggregation)

In [59]:
x = torch.arange(0,101, 10)
x

tensor([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [60]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [61]:
torch.max(x), x.max()

(tensor(100), tensor(100))

In [62]:
torch.mean(x.type(torch.float64)), x.type(torch.float32).mean()

(tensor(50., dtype=torch.float64), tensor(50.))

## **Note:** torch.mean() throws error if a tensor of int is passed, it must be converted to float first

In [63]:
torch.argmax(x), torch.argmin(x) #returns index

(tensor(10), tensor(0))

In [64]:
x[10] = 101001

In [65]:
x[10]

tensor(101001)

#### Reshaping, stacking, sqeezing and unsqeezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* Stacking - combining multiple tensors on tops of each other (vstack) or side by side (hstack)
* Sqeeze - remove all `1` dimentions from a tensor
* unsqueezing - add a `1` dimention to a target tensor
* permute - return a view of the input with dimentions permuted

In [66]:
x = torch.arange(1., 10., 0.5)
x,x.shape

(tensor([1.0000, 1.5000, 2.0000, 2.5000, 3.0000, 3.5000, 4.0000, 4.5000, 5.0000,
         5.5000, 6.0000, 6.5000, 7.0000, 7.5000, 8.0000, 8.5000, 9.0000, 9.5000]),
 torch.Size([18]))

In [67]:
x_reshaped = x.reshape(3,2,3)
x_reshaped, x_reshaped.shape


(tensor([[[1.0000, 1.5000, 2.0000],
          [2.5000, 3.0000, 3.5000]],
 
         [[4.0000, 4.5000, 5.0000],
          [5.5000, 6.0000, 6.5000]],
 
         [[7.0000, 7.5000, 8.0000],
          [8.5000, 9.0000, 9.5000]]]),
 torch.Size([3, 2, 3]))

In [68]:
z = x.view(2,3,3)
z, z.shape


(tensor([[[1.0000, 1.5000, 2.0000],
          [2.5000, 3.0000, 3.5000],
          [4.0000, 4.5000, 5.0000]],
 
         [[5.5000, 6.0000, 6.5000],
          [7.0000, 7.5000, 8.0000],
          [8.5000, 9.0000, 9.5000]]]),
 torch.Size([2, 3, 3]))

### changing z changes x (because a view of a tensor shares the same memory as the original tensor)

In [69]:
z[:,0] = 0
z,x

(tensor([[[0.0000, 0.0000, 0.0000],
          [2.5000, 3.0000, 3.5000],
          [4.0000, 4.5000, 5.0000]],
 
         [[0.0000, 0.0000, 0.0000],
          [7.0000, 7.5000, 8.0000],
          [8.5000, 9.0000, 9.5000]]]),
 tensor([0.0000, 0.0000, 0.0000, 2.5000, 3.0000, 3.5000, 4.0000, 4.5000, 5.0000,
         0.0000, 0.0000, 0.0000, 7.0000, 7.5000, 8.0000, 8.5000, 9.0000, 9.5000]))

In [70]:
# stacking tensors on top of each other
x = torch.arange(1,6)
x_stacked = torch.stack([x,x,x,x], dim = 0)
x_stacked

tensor([[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]])

In [71]:
x_stacked = torch.stack([x,x,x,x], dim = 1)
x_stacked

tensor([[1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3],
        [4, 4, 4, 4],
        [5, 5, 5, 5]])

In [72]:
a = torch.rand(3,3)
b = torch.rand(3,3)
c = torch.rand(3,3)

stacked = torch.stack([a,b,c], dim = 1)
stacked

tensor([[[0.4399, 0.3615, 0.2736],
         [0.9502, 0.5830, 0.9885],
         [0.7119, 0.0011, 0.8902]],

        [[0.4840, 0.1559, 0.0186],
         [0.0830, 0.3291, 0.1384],
         [0.9099, 0.0607, 0.3535]],

        [[0.8952, 0.7214, 0.6048],
         [0.9345, 0.4082, 0.3815],
         [0.3731, 0.0873, 0.8186]]])

In [73]:
# torch.squeeze removes all single dimentions from the traget vector


In [74]:
x_reshaped

tensor([[[0.0000, 0.0000, 0.0000],
         [2.5000, 3.0000, 3.5000]],

        [[4.0000, 4.5000, 5.0000],
         [0.0000, 0.0000, 0.0000]],

        [[7.0000, 7.5000, 8.0000],
         [8.5000, 9.0000, 9.5000]]])

In [75]:
x_reshaped.squeeze()

tensor([[[0.0000, 0.0000, 0.0000],
         [2.5000, 3.0000, 3.5000]],

        [[4.0000, 4.5000, 5.0000],
         [0.0000, 0.0000, 0.0000]],

        [[7.0000, 7.5000, 8.0000],
         [8.5000, 9.0000, 9.5000]]])

In [76]:
x_reshaped.squeeze().shape

torch.Size([3, 2, 3])

In [77]:
y = torch.rand(1,2,2,4,2,1,)

In [78]:
y

tensor([[[[[[0.4730],
            [0.2702]],

           [[0.1218],
            [0.9594]],

           [[0.5246],
            [0.8277]],

           [[0.9337],
            [0.4964]]],


          [[[0.1254],
            [0.3905]],

           [[0.3223],
            [0.0828]],

           [[0.2134],
            [0.9885]],

           [[0.0516],
            [0.4580]]]],



         [[[[0.3061],
            [0.0418]],

           [[0.1147],
            [0.4365]],

           [[0.6071],
            [0.9252]],

           [[0.1532],
            [0.3964]]],


          [[[0.4834],
            [0.2065]],

           [[0.4205],
            [0.4879]],

           [[0.7102],
            [0.3187]],

           [[0.8791],
            [0.8823]]]]]])

In [79]:
y.squeeze()

tensor([[[[0.4730, 0.2702],
          [0.1218, 0.9594],
          [0.5246, 0.8277],
          [0.9337, 0.4964]],

         [[0.1254, 0.3905],
          [0.3223, 0.0828],
          [0.2134, 0.9885],
          [0.0516, 0.4580]]],


        [[[0.3061, 0.0418],
          [0.1147, 0.4365],
          [0.6071, 0.9252],
          [0.1532, 0.3964]],

         [[0.4834, 0.2065],
          [0.4205, 0.4879],
          [0.7102, 0.3187],
          [0.8791, 0.8823]]]])

In [80]:
y.shape

torch.Size([1, 2, 2, 4, 2, 1])

In [81]:
y.squeeze().shape

torch.Size([2, 2, 4, 2])

In [82]:
y = torch.tensor([[1,3]])
y.shape

torch.Size([1, 2])

In [83]:
y_squeezed = y.squeeze()
y_squeezed


tensor([1, 3])

In [84]:
y_squeezed .shape

torch.Size([2])

# torch.unsqueeze() - adds a single dimention to a target tensor at a specific dimention

In [85]:
print(f'previous target{y_squeezed }')
print(f'previous shape{y_squeezed.shape }')

previous targettensor([1, 3])
previous shapetorch.Size([2])


In [86]:
y_unsqueezed = y_squeezed.unsqueeze(dim = 1)
print(f'new target{y_unsqueezed }')
print(f'new shape{y_unsqueezed.shape}')

new targettensor([[1],
        [3]])
new shapetorch.Size([2, 1])


# torch.permute() - returns a view of the original tensor with its dimentions permuted

In [87]:
x_original = torch.rand(size = (224,224,3))

x_permuted = x_original.permute(2,0,1)
x_permuted.shape

torch.Size([3, 224, 224])

In [88]:
x_original.shape

torch.Size([224, 224, 3])

In [89]:
x_original[0][0][0]

tensor(0.9618)

In [90]:
x_permuted[0][0][0]

tensor(0.9618)

In [91]:
x_permuted[0][0][0] = 1

In [92]:
x_original[0][0][0],x_permuted[0][0][0]

(tensor(1.), tensor(1.))

####Indexing (same as numpy)

In [93]:
x = torch.arange(1,10).reshape(1,3,3)

In [94]:
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [95]:
x.squeeze()

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [96]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [97]:
x[:,1,1]

tensor([5])

In [98]:
x[0,0,:]

tensor([1, 2, 3])

In [99]:
x[0,2,2]

tensor(9)

In [100]:
x[0,:,2]

tensor([3, 6, 9])

 #### PyTorch tensors & Numpy

In [101]:
array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [102]:
array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array).type(torch.float32)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

### Numpy's default is float64 and torch's is float32

### when converting from numpy to torch, type will be float64

In [103]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

RANDOM SEED

In [104]:
RANDOM_SEED = 67
torch.manual_seed(RANDOM_SEED)
random_tensor1 = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor2 = torch.rand(3,4)

print(random_tensor1)
print(random_tensor2)
print(random_tensor1 == random_tensor2)


tensor([[0.7380, 0.3646, 0.8673, 0.5464],
        [0.5885, 0.9785, 0.8875, 0.9903],
        [0.3595, 0.3245, 0.8871, 0.9991]])
tensor([[0.7380, 0.3646, 0.8673, 0.5464],
        [0.5885, 0.9785, 0.8875, 0.9903],
        [0.3595, 0.3245, 0.8871, 0.9991]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [105]:
!nvidia-smi

Mon Mar  2 10:46:08 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   47C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [109]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [110]:
torch.cuda.device_count()

1

## Putting tensors (and models) on the GPU

In [111]:
tensor = torch.tensor([1,2,3]) # default on the CPU

print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [112]:
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

## Moving tensors back to cpu

<p> if tensor is on GPU, can't transform it to numpy

In [115]:
tensor_on_gpu.numpy()


TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

<p> To fix the GPU with numpy issue, we can first set it to CPU

In [116]:
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])