In [1]:
import torch

In [2]:
import numpy as np

In [4]:
random_tensor = torch.rand(7,7)
random_tensor

tensor([[0.7249, 0.6111, 0.7350, 0.9592, 0.5943, 0.1113, 0.0913],
        [0.2959, 0.8799, 0.6398, 0.6073, 0.2420, 0.8555, 0.8524],
        [0.7713, 0.5687, 0.7108, 0.5310, 0.5307, 0.2465, 0.3063],
        [0.5986, 0.6514, 0.8884, 0.8200, 0.0583, 0.4397, 0.3021],
        [0.4957, 0.9649, 0.1539, 0.7090, 0.2612, 0.7805, 0.3397],
        [0.8082, 0.7213, 0.5867, 0.7375, 0.4556, 0.2978, 0.9839],
        [0.4164, 0.1916, 0.6960, 0.5955, 0.3713, 0.8627, 0.6782]])

In [5]:
tensor2 = torch.rand(1,7)

In [8]:
mul = torch.matmul(random_tensor, tensor2.T)
mul

tensor([[1.2135],
        [1.7420],
        [1.3535],
        [1.2590],
        [0.9891],
        [1.7781],
        [1.6527]])

In [16]:
RANDOM_SEED = 69

torch.manual_seed(RANDOM_SEED)
random_tensor = torch.rand(7,7)
torch.manual_seed(RANDOM_SEED)
tensor2 = torch.rand(1,7)

random_tensor,tensor2

(tensor([[0.8398, 0.8042, 0.1213, 0.5309, 0.6646, 0.4077, 0.0888],
         [0.2429, 0.7053, 0.6216, 0.9188, 0.0185, 0.8741, 0.0560],
         [0.9659, 0.0073, 0.3628, 0.4197, 0.6444, 0.0099, 0.5925],
         [0.9631, 0.6958, 0.9157, 0.5523, 0.2344, 0.3262, 0.4521],
         [0.7020, 0.6274, 0.0945, 0.8525, 0.3572, 0.7492, 0.3579],
         [0.5453, 0.8171, 0.0570, 0.4560, 0.0183, 0.5854, 0.6620],
         [0.0158, 0.5309, 0.9056, 0.6011, 0.6072, 0.5147, 0.7654]]),
 tensor([[0.8398, 0.8042, 0.1213, 0.5309, 0.6646, 0.4077, 0.0888]]))

In [17]:
mul = random_tensor @ tensor2.T
mul

tensor([[2.2644],
        [1.7081],
        [1.5688],
        [2.1016],
        [2.1328],
        [1.6736],
        [1.5506]])

In [26]:
torch.cuda.manual_seed(1234)

In [27]:
torch.rand(2,3)

tensor([[0.0570, 0.4560, 0.0183],
        [0.5854, 0.6620, 0.0158]])

In [28]:
torch.rand(2,3)

tensor([[0.5309, 0.9056, 0.6011],
        [0.6072, 0.5147, 0.7654]])

In [35]:
torch.cuda.manual_seed(1234)
x = torch.rand(2,3, device = 'cuda')
torch.cuda.manual_seed(1234)
y = torch.rand(2,3, device = 'cuda')

x,y

(tensor([[0.1272, 0.8167, 0.5440],
         [0.6601, 0.2721, 0.9737]], device='cuda:0'),
 tensor([[0.1272, 0.8167, 0.5440],
         [0.6601, 0.2721, 0.9737]], device='cuda:0'))

In [39]:
torch.manual_seed(1234)
A = torch.rand(2,3).to('cuda')
torch.manual_seed(1234)
B = torch.rand(2,3).to('cuda')

A,B

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'))

In [41]:
product = A @ B.T
product

tensor([[0.2299, 0.2161],
        [0.2161, 0.6287]], device='cuda:0')

In [42]:
max_val = torch.max(product)
min_val = torch.min(product)

print(f'Max Value: {max_val}, Min Value: {min_val} ')

Max Value: 0.628727912902832, Min Value: 0.21611443161964417 


In [48]:
torch.manual_seed(7)
new_rand_tensor = torch.rand(1,1,1,10)
print(f'New Tensor: {new_rand_tensor}, Shape: {new_rand_tensor.shape} ')


New Tensor: tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]), Shape: torch.Size([1, 1, 1, 10]) 


In [49]:

squeezed_tensor = new_rand_tensor.squeeze()
print(f'New Tensor: {squeezed_tensor}, Shape: {squeezed_tensor.shape} ')

New Tensor: tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]), Shape: torch.Size([10]) 
